before_install:
  - npm install -g npm

cache:
  directories:
    - node_modules

env:
  global:
    - secure: "ShkaiyDNXXJ4TMBP/yKJw16Tts1SuFRtOrOTbXETHz6Nbm1vQyQ39tKHxK/5v9/58BTfrdKU9P6EU1pqPM/O7hV64o8q/GP25EO+qwqxD76U/vegSwr1C2Yw4j74MP3S5pjFgD4tkXxX4MWLBuYKBiexlyFidN/5r0O6f6Lfovo="
    - secure: "OzvpbqjtWZG4Zdj4/uT/nSpZyXsUk1pjNQ9v93jR4eglUhd1q+E/h+C3FFmhTUpOWoV/M1bPnegDmOI1TrLvxxl1+3pJv2xVnLZfYPWEUV03ESBW1md9mLentjY2tnspgmU3PAoZIOyEC/uD+FU7hIH9bYp+vRLUgnzYd5EMXTU="

language: node_js

node_js:
  - 0.10

script: npm run test:browsers

sudo: false
